volume_path: "/Volumes/workspace/default/no_show_volume"

dataset_path: "/Volumes/workspace/default/no_show_volume/healthcare_noshows.csv"

bronze_table_path: "workspace.default.bronze_features"

silver_table_path: "workspace.default.silver_no_show_features"

train_scaled_dataset_path: "workspace.default.no_show_train_scaled_tbl"

test_scaled_dataset_path: "workspace.default.no_show_test_scaled_tbl"

lr_model_path: "workspace.default.noshows_logistic_regression"

rf_model_path: "workspace.default.noshows_random_forest"


mlflow:
  experiment_path: "/Users/asanders4205@gmail.com/no-show-prediction"

model_output_path: "workspace/default/models"

random_seed: 42